# Generated by Django 5.1.3 on 2024-11-11 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='report_files/'),
        ),
        migrations.AlterField(
            model_name='taskchek',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий '),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Ответ '),
        ),
        migrations.AlterField(
            model_name='taskstageanddata',
            name='check_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='taskstageanddata',
            name='completion_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='taskstageanddata',
            name='creation_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.DeleteModel(
            name='ReportFile',
        ),
    ]
