# Generated by Django 5.1.3 on 2024-11-12 00:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_taskreport_file_alter_taskchek_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='taskchek',
            name='check_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='taskreport',
            name='completion_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creation', models.BooleanField(default=True, verbose_name='Стадия создания')),
                ('is_completion', models.BooleanField(default=False, verbose_name='Стадия выполнения')),
                ('is_check', models.BooleanField(default=False, verbose_name='Стадия проверки')),
                ('task', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_data', to='django_app.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Даты и этапы задачи',
                'verbose_name_plural': 'Даты и этапы задачи',
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='TaskStageAndData',
        ),
    ]
