# Generated by Django 5.1.3 on 2024-11-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_task_creation_date_taskchek_check_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstage',
            name='is_creation',
        ),
    ]
